# Generated by Django 5.0.4 on 2024-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CMS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="amount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="record",
            name="amount_in_cents",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="record",
            name="est_trips",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="record",
            name="ljublana_trips",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="record",
            name="month",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="record",
            name="year",
            field=models.IntegerField(),
        ),
    ]
