# Generated by Django 5.0.4 on 2024-04-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CMS", "0002_alter_record_amount_alter_record_amount_in_cents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Records",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("amount", models.IntegerField()),
                ("amount_in_cents", models.FloatField()),
                ("net_in_cents", models.FloatField()),
                ("km_food_in_cents", models.FloatField()),
                ("ljublana_trips", models.IntegerField()),
                ("est_trips", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Record",
        ),
    ]
